package crud;
// Generated Apr 18, 2022 1:58:46 PM by Hibernate Tools 4.3.1



/**
 * Assessment generated by hbm2java
 */
public class Assessment  implements java.io.Serializable {


     private int id;
     private Student student;
     private Integer genKnowledge;
     private Integer numberConcept;
     private Integer oralLang;
     private Integer reading;
     private Integer structure;
     private Integer vocab;
     private Integer studySkills;
     private Integer comTask;
     private Integer numEst;
     private Integer geometry;
     private Integer algebra;
     private Integer statistics;
     private Integer langArtGrade4;
     private Integer mathGrade4;
     private Integer langArtGrade5;
     private Integer mathGrade5;
     private Integer abilityTest;
     private Integer mathGrade6;
     private Integer langArtGrade6curri;
     private Integer mathGrade6curri;
     private Integer science;
     private Integer socialStudies;
     private Integer writingDrawing;

    public Assessment() {
    }

	
    public Assessment(int id) {
        this.id = id;
    }
    public Assessment(int id, Student student, Integer genKnowledge, Integer numberConcept, Integer oralLang, Integer reading, Integer structure, Integer vocab, Integer studySkills, Integer comTask, Integer numEst, Integer geometry, Integer algebra, Integer statistics, Integer langArtGrade4, Integer mathGrade4, Integer langArtGrade5, Integer mathGrade5, Integer abilityTest, Integer mathGrade6, Integer langArtGrade6curri, Integer mathGrade6curri, Integer science, Integer socialStudies, Integer writingDrawing) {
       this.id = id;
       this.student = student;
       this.genKnowledge = genKnowledge;
       this.numberConcept = numberConcept;
       this.oralLang = oralLang;
       this.reading = reading;
       this.structure = structure;
       this.vocab = vocab;
       this.studySkills = studySkills;
       this.comTask = comTask;
       this.numEst = numEst;
       this.geometry = geometry;
       this.algebra = algebra;
       this.statistics = statistics;
       this.langArtGrade4 = langArtGrade4;
       this.mathGrade4 = mathGrade4;
       this.langArtGrade5 = langArtGrade5;
       this.mathGrade5 = mathGrade5;
       this.abilityTest = abilityTest;
       this.mathGrade6 = mathGrade6;
       this.langArtGrade6curri = langArtGrade6curri;
       this.mathGrade6curri = mathGrade6curri;
       this.science = science;
       this.socialStudies = socialStudies;
       this.writingDrawing = writingDrawing;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getGenKnowledge() {
        return this.genKnowledge;
    }
    
    public void setGenKnowledge(Integer genKnowledge) {
        this.genKnowledge = genKnowledge;
    }
    public Integer getNumberConcept() {
        return this.numberConcept;
    }
    
    public void setNumberConcept(Integer numberConcept) {
        this.numberConcept = numberConcept;
    }
    public Integer getOralLang() {
        return this.oralLang;
    }
    
    public void setOralLang(Integer oralLang) {
        this.oralLang = oralLang;
    }
    public Integer getReading() {
        return this.reading;
    }
    
    public void setReading(Integer reading) {
        this.reading = reading;
    }
    public Integer getStructure() {
        return this.structure;
    }
    
    public void setStructure(Integer structure) {
        this.structure = structure;
    }
    public Integer getVocab() {
        return this.vocab;
    }
    
    public void setVocab(Integer vocab) {
        this.vocab = vocab;
    }
    public Integer getStudySkills() {
        return this.studySkills;
    }
    
    public void setStudySkills(Integer studySkills) {
        this.studySkills = studySkills;
    }
    public Integer getComTask() {
        return this.comTask;
    }
    
    public void setComTask(Integer comTask) {
        this.comTask = comTask;
    }
    public Integer getNumEst() {
        return this.numEst;
    }
    
    public void setNumEst(Integer numEst) {
        this.numEst = numEst;
    }
    public Integer getGeometry() {
        return this.geometry;
    }
    
    public void setGeometry(Integer geometry) {
        this.geometry = geometry;
    }
    public Integer getAlgebra() {
        return this.algebra;
    }
    
    public void setAlgebra(Integer algebra) {
        this.algebra = algebra;
    }
    public Integer getStatistics() {
        return this.statistics;
    }
    
    public void setStatistics(Integer statistics) {
        this.statistics = statistics;
    }
    public Integer getLangArtGrade4() {
        return this.langArtGrade4;
    }
    
    public void setLangArtGrade4(Integer langArtGrade4) {
        this.langArtGrade4 = langArtGrade4;
    }
    public Integer getMathGrade4() {
        return this.mathGrade4;
    }
    
    public void setMathGrade4(Integer mathGrade4) {
        this.mathGrade4 = mathGrade4;
    }
    public Integer getLangArtGrade5() {
        return this.langArtGrade5;
    }
    
    public void setLangArtGrade5(Integer langArtGrade5) {
        this.langArtGrade5 = langArtGrade5;
    }
    public Integer getMathGrade5() {
        return this.mathGrade5;
    }
    
    public void setMathGrade5(Integer mathGrade5) {
        this.mathGrade5 = mathGrade5;
    }
    public Integer getAbilityTest() {
        return this.abilityTest;
    }
    
    public void setAbilityTest(Integer abilityTest) {
        this.abilityTest = abilityTest;
    }
    public Integer getMathGrade6() {
        return this.mathGrade6;
    }
    
    public void setMathGrade6(Integer mathGrade6) {
        this.mathGrade6 = mathGrade6;
    }
    public Integer getLangArtGrade6curri() {
        return this.langArtGrade6curri;
    }
    
    public void setLangArtGrade6curri(Integer langArtGrade6curri) {
        this.langArtGrade6curri = langArtGrade6curri;
    }
    public Integer getMathGrade6curri() {
        return this.mathGrade6curri;
    }
    
    public void setMathGrade6curri(Integer mathGrade6curri) {
        this.mathGrade6curri = mathGrade6curri;
    }
    public Integer getScience() {
        return this.science;
    }
    
    public void setScience(Integer science) {
        this.science = science;
    }
    public Integer getSocialStudies() {
        return this.socialStudies;
    }
    
    public void setSocialStudies(Integer socialStudies) {
        this.socialStudies = socialStudies;
    }
    public Integer getWritingDrawing() {
        return this.writingDrawing;
    }
    
    public void setWritingDrawing(Integer writingDrawing) {
        this.writingDrawing = writingDrawing;
    }




}


