package crud;
// Generated Apr 18, 2022 1:58:46 PM by Hibernate Tools 4.3.1



/**
 * Health generated by hbm2java
 */
public class Health  implements java.io.Serializable {


     private int id;
     private Student student;
     private String physicalDefects;
     private String asthmatic;
     private String urinaryDisoder;
     private String earProblem;
     private String eyeProblem;
     private String other;

    public Health() {
    }

	
    public Health(int id) {
        this.id = id;
    }
    public Health(int id, Student student, String physicalDefects, String asthmatic, String urinaryDisoder, String earProblem, String eyeProblem, String other) {
       this.id = id;
       this.student = student;
       this.physicalDefects = physicalDefects;
       this.asthmatic = asthmatic;
       this.urinaryDisoder = urinaryDisoder;
       this.earProblem = earProblem;
       this.eyeProblem = eyeProblem;
       this.other = other;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getPhysicalDefects() {
        return this.physicalDefects;
    }
    
    public void setPhysicalDefects(String physicalDefects) {
        this.physicalDefects = physicalDefects;
    }
    public String getAsthmatic() {
        return this.asthmatic;
    }
    
    public void setAsthmatic(String asthmatic) {
        this.asthmatic = asthmatic;
    }
    public String getUrinaryDisoder() {
        return this.urinaryDisoder;
    }
    
    public void setUrinaryDisoder(String urinaryDisoder) {
        this.urinaryDisoder = urinaryDisoder;
    }
    public String getEarProblem() {
        return this.earProblem;
    }
    
    public void setEarProblem(String earProblem) {
        this.earProblem = earProblem;
    }
    public String getEyeProblem() {
        return this.eyeProblem;
    }
    
    public void setEyeProblem(String eyeProblem) {
        this.eyeProblem = eyeProblem;
    }
    public String getOther() {
        return this.other;
    }
    
    public void setOther(String other) {
        this.other = other;
    }




}


