package crud;
// Generated Apr 18, 2022 1:58:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String middleName;
     private String lastName;
     private String birthCertNum;
     private Date dob;
     private Date dareReg;
     private String sportsHouse;
     private String club;
     private String gender;
     private String studentAddress;
     private String motherName;
     private String motherOccupation;
     private String motherTel;
     private String fatherName;
     private String fatherTel;
     private String fatherAddress;
     private String guardianName;
     private String guardianOccupation;
     private String guardianAddress;
     private String guardianTel;
     private byte[] photo;
     private Set healths = new HashSet(0);
     private Set assessments = new HashSet(0);
     private Set attendances = new HashSet(0);

    public Student() {
    }

	
    public Student(int id) {
        this.id = id;
    }
    public Student(int id, String firstName, String middleName, String lastName, String birthCertNum, Date dob, Date dareReg, String sportsHouse, String club, String gender, String studentAddress, String motherName, String motherOccupation, String motherTel, String fatherName, String fatherTel, String fatherAddress, String guardianName, String guardianOccupation, String guardianAddress, String guardianTel, byte[] photo, Set healths, Set assessments, Set attendances) {
       this.id = id;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.birthCertNum = birthCertNum;
       this.dob = dob;
       this.dareReg = dareReg;
       this.sportsHouse = sportsHouse;
       this.club = club;
       this.gender = gender;
       this.studentAddress = studentAddress;
       this.motherName = motherName;
       this.motherOccupation = motherOccupation;
       this.motherTel = motherTel;
       this.fatherName = fatherName;
       this.fatherTel = fatherTel;
       this.fatherAddress = fatherAddress;
       this.guardianName = guardianName;
       this.guardianOccupation = guardianOccupation;
       this.guardianAddress = guardianAddress;
       this.guardianTel = guardianTel;
       this.photo = photo;
       this.healths = healths;
       this.assessments = assessments;
       this.attendances = attendances;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getBirthCertNum() {
        return this.birthCertNum;
    }
    
    public void setBirthCertNum(String birthCertNum) {
        this.birthCertNum = birthCertNum;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getDareReg() {
        return this.dareReg;
    }
    
    public void setDareReg(Date dareReg) {
        this.dareReg = dareReg;
    }
    public String getSportsHouse() {
        return this.sportsHouse;
    }
    
    public void setSportsHouse(String sportsHouse) {
        this.sportsHouse = sportsHouse;
    }
    public String getClub() {
        return this.club;
    }
    
    public void setClub(String club) {
        this.club = club;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getStudentAddress() {
        return this.studentAddress;
    }
    
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress;
    }
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }
    public String getMotherOccupation() {
        return this.motherOccupation;
    }
    
    public void setMotherOccupation(String motherOccupation) {
        this.motherOccupation = motherOccupation;
    }
    public String getMotherTel() {
        return this.motherTel;
    }
    
    public void setMotherTel(String motherTel) {
        this.motherTel = motherTel;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getFatherTel() {
        return this.fatherTel;
    }
    
    public void setFatherTel(String fatherTel) {
        this.fatherTel = fatherTel;
    }
    public String getFatherAddress() {
        return this.fatherAddress;
    }
    
    public void setFatherAddress(String fatherAddress) {
        this.fatherAddress = fatherAddress;
    }
    public String getGuardianName() {
        return this.guardianName;
    }
    
    public void setGuardianName(String guardianName) {
        this.guardianName = guardianName;
    }
    public String getGuardianOccupation() {
        return this.guardianOccupation;
    }
    
    public void setGuardianOccupation(String guardianOccupation) {
        this.guardianOccupation = guardianOccupation;
    }
    public String getGuardianAddress() {
        return this.guardianAddress;
    }
    
    public void setGuardianAddress(String guardianAddress) {
        this.guardianAddress = guardianAddress;
    }
    public String getGuardianTel() {
        return this.guardianTel;
    }
    
    public void setGuardianTel(String guardianTel) {
        this.guardianTel = guardianTel;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Set getHealths() {
        return this.healths;
    }
    
    public void setHealths(Set healths) {
        this.healths = healths;
    }
    public Set getAssessments() {
        return this.assessments;
    }
    
    public void setAssessments(Set assessments) {
        this.assessments = assessments;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


